algoritmo "calcular media"
// Função : calcular a média de 2 notas
// Autor :  prof.Anderson Vanin
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2,media:real
inicio
// dados de entrada
escreval("entre com um valor para p1: ")
leia(p1)
escreval("entre com um valor para p2: ")
leia(p2)
// fim dos dados de entrada
//processamento
media <- (p1+p2)/2
//fim de saida
escreval ("a media do aluno média do aluno é ",media)
//fim dos dados de saida

fimalgoritmo
