algoritmo "nome clube futebol"
// Função :
// Autor :
// Data : 16/08/2022
// Seção de Declarações
var
time:caracter
inicio
escreval("Escreva seu time")
leia(time)
escolha time
 caso "Palmeiras","São Paulo","Corinthians","Santos"
  escreval("EIXO SP")
 caso "Botafogo","Flamengo","Vasco","Fluminense"
  escreval("eixo RJ")
 outrocaso
  escreval("INVÁLIDO")
fimescolha
fimalgoritmo
