algoritmo "calcular media"
// Função : calcular a média de 2 notas
// Autor :  prof.Anderson Vanin
// Data : 26/04/2022
// Seção de Declarações 
var
valor,qtde,vt:real
inicio
// dados de entrada
escreval("entre com um valor para valor: ")
leia(valor)
escreval("entre com um valor para qtde: ")
leia(qtde)
// fim dos dados de entrada
//processamento
vt <- (valor*qtde)
//fim de saida
escreval ("valor total das peças é ",vt)
//fim dos dados de saida

fimalgoritmo
